"""Integration tests that drive the Flet wizard headlessly.

See ``tests/support/`` for the FakePage harness, scenario loader, and provider
mocks. Fixtures live in ``tests/fixtures/gui/scenarios/`` and are generated by
``scripts/gen_gui_fixtures.py`` from archived rips (plus hand-authored cases).
"""
