"""Capture and load folder snapshots for offline debugging and testing.

A snapshot is a JSON file containing the full metadata of a scanned folder
(durations, streams, chapters, file sizes) without any actual media data.
This lets users share their folder layout for bug reports, and lets
developers replay real scenarios in dry-run mode.
"""

from __future__ import annotations

import dataclasses
import json
import logging
import platform
import shutil
from datetime import datetime, timezone
from pathlib import Path

from riplex.models import ScannedDisc, ScannedFile
from riplex.scanner import scan_folder

log = logging.getLogger(__name__)

SNAPSHOT_VERSION = 1
SNAPSHOT_VERSION_V2 = 2

_README_TEXT = """\
This folder contains debug information generated by riplex.
These files help developers reproduce and diagnose issues.

If you are filing a bug report, zip this folder and attach it to your issue:
https://github.com/AnyCredit5518/riplex/issues/new?template=bug_report.yml

Files you may find here:
  riplex-rip.snapshot.json   - Disc info, metadata, and title classifications
  riplex-scan.snapshot.json  - Scanned file metadata (durations, streams, etc.)
  riplex-rip.manifest.json   - Map of ripped title indexes to output filenames
  riplex.log                 - Debug log from the most recent session
"""


def _get_version() -> str:
    """Return the riplex version string, or 'unknown' if unavailable."""
    try:
        from importlib.metadata import version
        return version("riplex")
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# Debug directory
# ---------------------------------------------------------------------------


def get_debug_dir(output_dir: Path) -> Path:
    """Return (and create) the ``_riplex/`` debug folder for *output_dir*.

    The folder is placed at the title level (parent of per-disc folders),
    e.g. ``E:\\Media\\_MakeMKV\\Movie (Year)\\_riplex\\``.
    The underscore prefix ensures Plex ignores it.
    """
    debug_dir = output_dir / "_riplex"
    debug_dir.mkdir(parents=True, exist_ok=True)

    readme = debug_dir / "README.txt"
    if not readme.exists():
        readme.write_text(_README_TEXT, encoding="utf-8")

    return debug_dir


def copy_debug_log(debug_dir: Path) -> Path | None:
    """Copy the current session's ``riplex.log`` into *debug_dir*.

    Returns the destination path, or ``None`` if the log wasn't found.
    """
    import tempfile

    log_src = Path(tempfile.gettempdir()) / "riplex" / "riplex.log"
    if not log_src.exists():
        log.debug("No debug log found at %s", log_src)
        return None

    dest = debug_dir / "riplex.log"
    try:
        shutil.copy2(log_src, dest)
        log.info("Copied debug log to %s", dest)
        return dest
    except OSError as exc:
        log.warning("Failed to copy debug log: %s", exc)
        return None


# ---------------------------------------------------------------------------
# V2 rip snapshot (disc info + metadata for troubleshooting)
# ---------------------------------------------------------------------------


def _v2_envelope(snapshot_type: str, data: dict) -> dict:
    """Wrap *data* in a v2 snapshot envelope."""
    return {
        "snapshot_version": SNAPSHOT_VERSION_V2,
        "type": snapshot_type,
        "created": datetime.now(timezone.utc).isoformat(),
        "riplex_version": _get_version(),
        "platform": platform.platform(),
        "data": data,
    }


def save_rip_snapshot(
    debug_dir: Path,
    disc_info,
    *,
    canonical: str = "",
    year: int | None = None,
    is_movie: bool = True,
    movie_runtime: int | None = None,
    release_name: str = "",
    discs: list | None = None,
    ripped_titles: list[int] | None = None,
) -> Path | None:
    """Write ``riplex-rip.snapshot.json`` into *debug_dir*.

    Returns the path on success, or ``None`` on failure.
    """
    try:
        data = {
            "disc_name": disc_info.disc_name,
            "title_count": len(disc_info.titles),
            "titles": [
                {
                    "index": t.index,
                    "duration_seconds": t.duration_seconds,
                    "resolution": t.resolution,
                    "size_bytes": t.size_bytes,
                    "chapters": getattr(t, "chapter_count", t.chapters if hasattr(t, "chapters") else None),
                }
                for t in disc_info.titles
            ],
            "tmdb": {
                "canonical_title": canonical,
                "year": year,
                "type": "movie" if is_movie else "tv",
                "movie_runtime": movie_runtime,
            },
            "dvdcompare": {
                "release": release_name,
                "disc_count": len(discs) if discs else 0,
                "discs": [
                    {
                        "number": d.number,
                        "episode_count": len(d.episodes),
                        "extra_count": len(d.extras),
                    }
                    for d in (discs or [])
                ],
            },
            "ripped_titles": ripped_titles or [],
        }
        snapshot = _v2_envelope("rip", data)
        out = debug_dir / "riplex-rip.snapshot.json"
        out.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
        log.info("Wrote rip snapshot: %s", out)
        return out
    except Exception as exc:
        log.warning("Failed to write rip snapshot: %s", exc)
        return None


def save_rip_manifest(
    debug_dir: Path,
    manifest: dict,
) -> Path | None:
    """Write ``riplex-rip.manifest.json`` into *debug_dir*.

    Returns the path on success, or ``None`` on failure.
    """
    try:
        out = debug_dir / "riplex-rip.manifest.json"
        out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        log.info("Wrote rip manifest: %s", out)
        return out
    except Exception as exc:
        log.warning("Failed to write rip manifest: %s", exc)
        return None


def save_scan_snapshot(
    debug_dir: Path,
    folder: Path,
    discs: list[ScannedDisc],
) -> Path | None:
    """Write ``riplex-scan.snapshot.json`` into *debug_dir*.

    Returns the path on success, or ``None`` on failure.
    """
    try:
        data = {
            "source_folder": str(folder),
            "groups": [
                {
                    "folder_name": disc.folder_name,
                    "files": [_file_to_dict(f) for f in disc.files],
                }
                for disc in discs
            ],
        }
        snapshot = _v2_envelope("scan", data)
        out = debug_dir / "riplex-scan.snapshot.json"
        out.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
        log.info("Wrote scan snapshot: %s", out)
        return out
    except Exception as exc:
        log.warning("Failed to write scan snapshot: %s", exc)
        return None


def capture(folder: Path) -> dict:
    """Scan *folder* and return a snapshot dict ready for JSON serialization."""
    discs = scan_folder(folder)

    return {
        "snapshot_version": SNAPSHOT_VERSION,
        "created": datetime.now(timezone.utc).isoformat(),
        "source_folder": str(folder),
        "groups": [
            {
                "folder_name": disc.folder_name,
                "files": [
                    _file_to_dict(f) for f in disc.files
                ],
            }
            for disc in discs
        ],
    }


def capture_from_scanned(folder: Path, discs: list[ScannedDisc]) -> dict:
    """Build a snapshot dict from already-scanned data (no rescan)."""
    return {
        "snapshot_version": SNAPSHOT_VERSION,
        "created": datetime.now(timezone.utc).isoformat(),
        "source_folder": str(folder),
        "groups": [
            {
                "folder_name": disc.folder_name,
                "files": [_file_to_dict(f) for f in disc.files],
            }
            for disc in discs
        ],
    }


def save(folder: Path, output: Path) -> Path:
    """Scan *folder*, write a snapshot JSON to *output*, return the path."""
    data = capture(folder)
    output.write_text(json.dumps(data, indent=2), encoding="utf-8")
    log.info("Snapshot saved: %s (%d group(s), %d file(s))",
             output, len(data["groups"]),
             sum(len(g["files"]) for g in data["groups"]))
    return output


def save_from_scanned(folder: Path, discs: list[ScannedDisc], output: Path) -> Path:
    """Write a snapshot JSON from already-scanned data, return the path."""
    data = capture_from_scanned(folder, discs)
    output.write_text(json.dumps(data, indent=2), encoding="utf-8")
    log.info("Snapshot saved: %s (%d group(s), %d file(s))",
             output, len(data["groups"]),
             sum(len(g["files"]) for g in data["groups"]))
    return output


def load(snapshot_path: Path) -> list[ScannedDisc]:
    """Load a snapshot JSON and return ScannedDisc objects.

    Supports both v1 snapshots (flat structure) and v2 snapshots
    (envelope with ``type`` and ``data`` keys).

    File paths in the returned objects are synthetic (relative to the
    snapshot's original source folder) since the actual files don't exist.
    """
    raw = json.loads(snapshot_path.read_text(encoding="utf-8"))

    version = raw.get("snapshot_version", 0)
    if version == SNAPSHOT_VERSION_V2:
        snap_type = raw.get("type", "")
        if snap_type == "scan":
            groups = raw.get("data", {}).get("groups", [])
        else:
            raise ValueError(
                f"Cannot load snapshot type '{snap_type}' as ScannedDisc list"
            )
    elif version == SNAPSHOT_VERSION:
        groups = raw.get("groups", [])
    else:
        raise ValueError(
            f"Unsupported snapshot version {version} (expected {SNAPSHOT_VERSION} or {SNAPSHOT_VERSION_V2})"
        )

    discs: list[ScannedDisc] = []
    for group in groups:
        files = [_dict_to_file(f) for f in group["files"]]
        discs.append(ScannedDisc(folder_name=group["folder_name"], files=files))

    log.info("Loaded snapshot: %s (%d group(s), %d file(s))",
             snapshot_path, len(discs),
             sum(len(d.files) for d in discs))
    return discs


def _file_to_dict(f: ScannedFile) -> dict:
    """Serialize a ScannedFile to a plain dict, keeping only metadata."""
    return {
        "name": f.name,
        "duration_seconds": f.duration_seconds,
        "size_bytes": f.size_bytes,
        "stream_count": f.stream_count,
        "stream_fingerprint": f.stream_fingerprint,
        "chapter_count": f.chapter_count,
        "chapter_durations": f.chapter_durations,
        "title_tag": f.title_tag,
        "max_width": f.max_width,
        "max_height": f.max_height,
        "organized_tag": f.organized_tag,
        "perceptual_hash": f.perceptual_hash,
    }


def _dict_to_file(d: dict) -> ScannedFile:
    """Deserialize a dict back into a ScannedFile.

    The ``path`` field is set to a synthetic value since the real file
    doesn't exist on the machine loading the snapshot.
    """
    return ScannedFile(
        name=d["name"],
        path=d["name"],  # synthetic; real path doesn't exist
        duration_seconds=d.get("duration_seconds", 0),
        size_bytes=d.get("size_bytes", 0),
        stream_count=d.get("stream_count", 0),
        stream_fingerprint=d.get("stream_fingerprint", ""),
        chapter_count=d.get("chapter_count", 0),
        chapter_durations=d.get("chapter_durations", []),
        title_tag=d.get("title_tag"),
        max_width=d.get("max_width", 0),
        max_height=d.get("max_height", 0),
        organized_tag=d.get("organized_tag"),
        perceptual_hash=d.get("perceptual_hash"),
    )


# ---------------------------------------------------------------------------
# Organized marker — records that a folder has been processed
# ---------------------------------------------------------------------------

ORGANIZED_MARKER_NAME = "organized.json"


@dataclasses.dataclass
class OrganizedMarker:
    """Information stored in the organized marker file."""

    title: str
    organized_at: str
    file_count: int = 0
    output_root: str = ""


def save_organized_marker(
    folder: Path,
    *,
    title: str,
    file_count: int = 0,
    output_root: str = "",
) -> Path | None:
    """Write an ``organized.json`` marker into ``<folder>/_riplex/``.

    Returns the marker path on success, or ``None`` on failure.
    """
    try:
        debug_dir = get_debug_dir(folder)
        data = {
            "title": title,
            "organized_at": datetime.now(timezone.utc).isoformat(),
            "riplex_version": _get_version(),
            "file_count": file_count,
            "output_root": output_root,
        }
        out = debug_dir / ORGANIZED_MARKER_NAME
        out.write_text(json.dumps(data, indent=2), encoding="utf-8")
        log.info("Wrote organized marker: %s", out)
        return out
    except Exception as exc:
        log.warning("Failed to write organized marker: %s", exc)
        return None


def load_organized_marker(folder: Path) -> OrganizedMarker | None:
    """Read the organized marker from ``<folder>/_riplex/organized.json``.

    Returns an :class:`OrganizedMarker` if the file exists, or ``None``.
    """
    marker_path = folder / "_riplex" / ORGANIZED_MARKER_NAME
    if not marker_path.is_file():
        return None
    try:
        raw = json.loads(marker_path.read_text(encoding="utf-8"))
        return OrganizedMarker(
            title=raw.get("title", ""),
            organized_at=raw.get("organized_at", ""),
            file_count=raw.get("file_count", 0),
            output_root=raw.get("output_root", ""),
        )
    except Exception as exc:
        log.warning("Failed to read organized marker: %s", exc)
        return None
